"""timetable: boards, periods, entries, duty & gate rotas

Revision ID: 94158298b2c1
Revises: 6e333dabeb89
Create Date: 2026-07-27 12:32:42.314410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94158298b2c1'
down_revision = '6e333dabeb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_shifts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('time', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gate_pickup_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('date_range', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('layout', sa.String(length=20), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('shift_id', sa.String(length=40), nullable=False),
    sa.Column('staff_name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['duty_shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gate_pickup_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('staff_name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['gate_pickup_weeks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'day', name='uq_gate_week_day')
    )
    op.create_table('timetable_legend_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['timetable_boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'code', name='uq_legend_board_code')
    )
    op.create_table('timetable_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=20), nullable=False),
    sa.Column('end', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['timetable_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_board_classes',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['timetable_boards.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['academic_classes.id'], ),
    sa.PrimaryKeyConstraint('board_id', 'class_id')
    )
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=40), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['timetable_boards.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['academic_classes.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['timetable_periods.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'day', 'period_id', 'class_id', name='uq_timetable_cell')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable_entries')
    op.drop_table('timetable_board_classes')
    op.drop_table('timetable_periods')
    op.drop_table('timetable_legend_entries')
    op.drop_table('gate_pickup_entries')
    op.drop_table('duty_entries')
    op.drop_table('timetable_boards')
    op.drop_table('gate_pickup_weeks')
    op.drop_table('duty_shifts')
    # ### end Alembic commands ###
