"""staff: signature_path

Revision ID: a1b2c9d4e5f6
Revises: b1c2d3e4f5a6
Create Date: 2026-08-18 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c9d4e5f6'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_path', sa.String(length=260), nullable=False, server_default=''))

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('signature_path', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('signature_path')
    # ### end Alembic commands ###