"""staff/school: store photo, signature and logo bytes in the database

Render's free web service filesystem is wiped on every restart/redeploy, so
images previously saved only under static/ (staff photos, staff signatures,
the school logo) could vanish without warning. This adds columns to hold the
image bytes directly in Postgres, which does persist, alongside the existing
*_path columns (kept for the sample images shipped in the repo itself).

Revision ID: b4d8e1f2a3c5
Revises: d7e8f9a0b1c2
Create Date: 2026-09-09 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d8e1f2a3c5'
down_revision = 'd7e8f9a0b1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('photo_mimetype', sa.String(length=80), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('signature_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('signature_mimetype', sa.String(length=80), nullable=False, server_default=''))

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('photo_mimetype', server_default=None)
        batch_op.alter_column('signature_mimetype', server_default=None)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('logo_mimetype', sa.String(length=80), nullable=False, server_default=''))

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.alter_column('logo_mimetype', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('logo_mimetype')
        batch_op.drop_column('logo_data')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('signature_mimetype')
        batch_op.drop_column('signature_data')
        batch_op.drop_column('photo_mimetype')
        batch_op.drop_column('photo_data')
    # ### end Alembic commands ###