"""students: gender

Revision ID: c7d8e2f4a1b9
Revises: a3f7c1e9b2d4
Create Date: 2026-09-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d8e2f4a1b9'
down_revision = 'a3f7c1e9b2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False, server_default=''))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('gender', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('gender')
    # ### end Alembic commands ###