"""reports: comments, report batches, published reports

Revision ID: 35f3614378e6
Revises: a5382b7b6d55
Create Date: 2026-07-25 08:30:41.062826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e8f9a0b1c2'
down_revision = 'e2f4a7c1d9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('comment_type', sa.String(length=40), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('teacher', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=60), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('publish_here', sa.Boolean(), nullable=False),
    sa.Column('publish_sms', sa.Boolean(), nullable=False),
    sa.Column('publish_email', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['academic_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=60), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['academic_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_report_students',
    sa.Column('published_report_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['published_report_id'], ['published_reports.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('published_report_id', 'student_id')
    )
    op.create_table('report_batch_students',
    sa.Column('report_batch_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_batch_id'], ['report_batches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('report_batch_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_batch_students')
    op.drop_table('published_report_students')
    op.drop_table('report_batches')
    op.drop_table('published_reports')
    op.drop_table('report_comments')
    # ### end Alembic commands ###
