"""staff: temp_password_plain

Revision ID: e2f4a7c1d9b3
Revises: a1b2c9d4e5f6
Create Date: 2026-08-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f4a7c1d9b3'
down_revision = 'a1b2c9d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_password_plain', sa.String(length=255), nullable=False, server_default=''))

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('temp_password_plain', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('temp_password_plain')
    # ### end Alembic commands ###