"""report_comments: report_stage

Revision ID: efa016f71bc6
Revises: c7d8e2f4a1b9
Create Date: 2026-09-11 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa016f71bc6'
down_revision = 'c7d8e2f4a1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_stage', sa.String(length=60), nullable=False, server_default='End of term'))

    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.alter_column('report_stage', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.drop_column('report_stage')
    # ### end Alembic commands ###