"""staff: photo_path

Revision ID: f1a6c9d2e3b7
Revises: c32b42a43d0e
Create Date: 2026-08-18 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a6c9d2e3b7'
down_revision = 'c32b42a43d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=260), nullable=False, server_default=''))

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('photo_path', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('photo_path')
    # ### end Alembic commands ###